<?php

namespace AppBundle\Repository;

/**
 * actionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class actionRepository extends \Doctrine\ORM\EntityRepository
{
}
