<?php

namespace AppBundle\Repository;

/**
 * boite_mailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class boite_mailRepository extends \Doctrine\ORM\EntityRepository
{
}
