<?php

namespace AppBundle\Repository;

/**
 * joueursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class joueursRepository extends \Doctrine\ORM\EntityRepository
{
}
