<?php

namespace AppBundle\Repository;

/**
 * personnagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personnagesRepository extends \Doctrine\ORM\EntityRepository
{
}
